
KAFKA_NODES = 3
NETWORK_PREFIX = "192.168.34."

Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true
    config.vm.box = "ubuntu/bionic64"
    (1..KAFKA_NODES).each do |i|
        config.vm.define "kafka-node-#{i}" do |node|
            node.vm.network "private_network", ip: NETWORK_PREFIX + "#{i + 100}"
            node.vm.provision :shell, :path => "scripts/install_jdk.sh"
            node.vm.provision :shell, :path => "scripts/install_kafka.sh"
            node.vm.provision :shell, :path => "scripts/configure_zookeeper_cluster.sh", :args => "#{KAFKA_NODES} #{i}"
            node.vm.provision :shell, :path => "scripts/configure_kafka_cluster.sh", :args => "#{KAFKA_NODES} #{i}"
            node.vm.provision :shell, :path => "scripts/start_kafka.sh"
            node.vm.provision "shell", inline: "echo 'Node kafka-node-#{i} is up and running!'"
            node.vm.hostname = "kafka-node-#{i}"
            node.vm.provider :virtualbox do |vb|
                vb.name = "kafka-node-#{i}"
            end
        end
    end  

    config.vm.provider "virtualbox" do |v|
        #  This setting controls how much cpu time a virtual CPU can use. A value of 50 implies a single virtual CPU can use up to 50% of a single host CPU.
        # v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        v.cpus = 1
        v.memory = "2048"
    end

end   