
KAFKA_NODES = 1
NETWORK_PREFIX = "192.168.34."

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    (1..KAFKA_NODES).each do |i|
        config.vm.define "kafka-node-#{i}" do |node|
            node.vm.network "private_network", ip: NETWORK_PREFIX + "#{i + 100}"
            node.vm.provision :shell, :path => "scripts/install_jdk.sh"
            node.vm.provision :shell, :path => "scripts/install_kafka.sh"
            node.vm.provision "shell", inline: "echo hello from node kafka-node-#{i}"
            node.vm.hostname = "kafka-node-#{i}"
            node.vm.provider :virtualbox do |vb|
                vb.name = "kafka-node-#{i}"
            end
        end
    end  

    config.vm.provider "virtualbox" do |v|
        #  This setting controls how much cpu time a virtual CPU can use. A value of 50 implies a single virtual CPU can use up to 50% of a single host CPU.
        # v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        v.cpus = 1
        v.memory = "2048"
    end

end   